config/routes.rb
Rails.application.routes.draw do
  get 'movies/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get "lists", to: "lists#index"
  # get "lists/new", to: "lists#new", as: :new_lists
  # post "lists", to: "lists#create"
  # get "lists/:id", to: "lists#show", as: :list
  resources :lists, only: [:create, :index, :new, :show, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord

  scope :status, -> (stat) { where(status: stat) }

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true
  has_one_attached :photo

  STATUSES = %w[pending approved rejected].freeze

  def approved?
    status == 'approved'
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[create]

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name, collection: List::STATUSES %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/random/?movies);">
  <div class="container">
    <h1><strong>Save any kind of movies</strong></h1>
    <p>Classic</p>
  </div>
</div>
<div class="container my-5">
  <div class="d-flex justify-content-between">
    <h1>My Lists</h1>
    <p>
      <%= link_to "Create a movie list", new_list_path, class:"btn btn-success btn-flat" %>
    </p>
  </div>
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
        <%= link_to list.name, list_path(list) %>
        <%= link_to "X",
          list_path(list),
          class: 'close',
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
        %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container mt-5">
  <h1>Create new list</h1>
  <%= render "form", list: @list %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key %>')"></div>

<div class="container mt-5">
  <div class="d-flex justify-content-between">
    <h1><%= @list.name %></h1>
  </div>
  <hr>
  <div class="row">
    <% @bookmarks.each do |bookmark| %>
      <div class="col-sm-6 mt-2">
        <div class="card">
          <img class="card-img-top" src="<%= bookmark.movie.poster_url %>" alt="Card image cap">
            <div class="card-body">
              <h6 class="card-title"><%= link_to bookmark.movie.title, list_path(bookmark.movie) %> ・ <%= bookmark.movie.rating %> ⭐️ </h5>
              <p class="card-text"><%= bookmark.movie.overview %></p>
              <p class="card-text">⎷ <%= bookmark.comment %></p>
            </div>
          <%= link_to "X",
            bookmark_path(bookmark),
            class: 'close',
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
          %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<br>
<hr>
<div class="container my-5">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <%= image_tag "popcorn.png", alt: "popcorn", width: 200 %>
    </a>
    <div>
      <%= link_to "My lists", lists_path, style: "text-decoration:none; color: grey;" %>
      <%= link_to "New list", new_list_path, style: "text-decoration:none; color: grey;" %>
    </div>
  </div>
</div>